@startuml
skinparam classAttributeIconSize 0
skinparam monochrome false


class PesquisaSatisfacao {
  +id: string
  +pergunta: string
  +ordemServicoId: number
  +resposta: string
  +obrigatoria: boolean
  +tipo: string
}


class OrdemServico {
  +id: string
}

PesquisaSatisfacao "1..*" --* "1" OrdemServico : ordemServicoId

@enduml
